routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth/login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
// Route::get('/companies', 'CompaniesController@index')->name('companies');
// Route::post('/companies/store', 'CompaniesController@store')->name('companies-store');
Route::resource('companies', 'CompaniesController');
Route::resource('employees', 'EmployeesController');
// Route::get('/employees', 'EmployeesController@index')->name('employees');

app/Http/Controllers/CompaniesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use App\Companies;
use Illuminate\Support\Facades\Storage;
use File;

class CompaniesController extends Controller
{

    public function __construct() {
        $this->middleware("auth");
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companies = DB::table('companies')->paginate(5);
        return view('companies.index', ['companies' => $companies]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('companies.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'email' => 'required|email|unique:companies',
            'logo' => 'required|dimensions:min_width=100,min_height=100|mimes:png|max:2048',
            'website' => 'required',
        ]);

        $file = $request->file('logo');
        $logo = time().'.'.request()->logo->getClientOriginalExtension();
     
        $companies = new Companies([
            'name' => $request->get('name'),
            'email'=> $request->get('email'),
            'logo'=> $logo,
            'website'=> $request->get('website')
        ]);
        $companies->save();
        // print_r($file->getRealPath());die;
        // request()->logo->move(public_path('images'), $logo);
        Storage::disk('local')->put('company'.'/'.$logo, File::get($file));
        return redirect('/companies')->with('success', 'Companies has been added Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $companies = Companies::find($id);
        return view('companies.detail', ['companies' => $companies]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $companies = Companies::find($id);
        return view('companies.edit', ['companies' => $companies]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $companies = Companies::find($id);

        if (@$request->all()['logo'] != null) {
            if ($companies->email == $request->get('email')) {
                $request->validate([
                    'name' => 'required',
                    'email' => 'required|email',
                    'logo' => 'required|dimensions:min_width=100,min_height=100|mimes:png|max:2048',
                    'website' => 'required',
                ]);
            } else {
                $request->validate([
                    'name' => 'required',
                    'email' => 'required|email|unique:companies,email,{$this->post->id}',
                    'logo' => 'required|dimensions:min_width=100,min_height=100|mimes:png|max:2048',
                    'website' => 'required',
                ]);
            }
        } else {
            if ($companies->email == $request->get('email')) {
                $request->validate([
                    'name' => 'required',
                    'email' => 'required|email',
                    'website' => 'required',
                ]);
            } else {
                $request->validate([
                    'name' => 'required',
                    'email' => 'required|email|unique:companies,email,{$this->post->id}',
                    'website' => 'required',
                ]);
            }
        }

        $companies->name = $request->get('name');
        $companies->email = $request->get('email');
        $companies->website = $request->get('website');
        $old_logo = $companies->logo;

        if (@$request->all()['logo'] != null) {
            $file = $request->file('logo');
            $logo = time().'.'.request()->logo->getClientOriginalExtension();
            $companies->logo = $logo;
            Storage::disk('local')->put('company'.'/'.$logo, File::get($file));
            Storage::delete('/public/company/'.$old_logo); 
        }
        $companies->update();

        return redirect('/companies')->with('success', 'Companies has been updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $companies = Companies::find($id);
        Storage::delete('/public/company/'.$companies->logo); 
        $companies->delete();

        return redirect('/companies')->with('success', 'Companies has been deleted Successfully');
    }
}

resources/views/companies/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
      <h1>
        Companies
        <small>preview of simple tables</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Companies</a></li>
        <li class="active">Companies Create</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <!-- Horizontal Form -->
          <div class="box box-default">
            <div class="box-header with-border">
              <h3 class="box-title">Companies Create</h3>
            </div>
            <!-- /.box-header -->

            @if ($errors->any())
              <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                      <li>{{ $error }}</li>
                    @endforeach
                </ul>
              </div><br />
            @endif
            <!-- form start -->
            <form class="form-horizontal" method="POST" action="{{ route('companies.store') }}" enctype="multipart/form-data">
              @csrf
              <div class="box-body">
                <div class="form-group">
                  <label for="name" class="col-sm-2 control-label">Name</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control" name="name" placeholder="Name" value="{{ old('name') }}">
                  </div>
                </div>
                <div class="form-group">
                  <label for="email" class="col-sm-2 control-label">Email</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control" name="email" placeholder="Email" value="{{ old('email') }}">
                  </div>
                </div>
                <div class="form-group">
                  <label for="logo" class="col-sm-2 control-label">Logo</label>
                  <div class="col-sm-8">
                    <input type="file" id="logo" class="form-control" name="logo" placeholder="Logo" value="{{ old('logo') }}">
                    <br>
                    <img src="#" id="preview-logo" width="200px" />
                  </div>
                </div>
                <div class="form-group">
                  <label for="website" class="col-sm-2 control-label">Website</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control" name="website" placeholder="Website" value="{{ old('website') }}">
                  </div>
                </div>
              </div>
              <!-- /.box-body -->
              <div class="box-footer">
                <a href="{{ route('companies.index') }}" type="button" class="btn btn-default"><i class="fa fa-arrow-left"></i> Back</a>
                <button type="submit" class="btn btn-success pull-right"><i class="fa fa-save"></i> Save</button>
              </div>
              <!-- /.box-footer -->
            </form>
          </div>
        </div>
      </div>
    </section>
@endsection

@section('scripts')
<script type="text/javascript">
  function readURL(input) {
      if (input.files && input.files[0]) {
          var reader = new FileReader();
          
          reader.onload = function (e) {
              $('#preview-logo').attr('src', e.target.result);
          }
          
          reader.readAsDataURL(input.files[0]);
      }
  }
  
  $("#logo").change(function(){
      readURL(this);
  });
</script>
@endsection

resources/views/companies/detail.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
      <h1>
        Companies
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Companies</a></li>
        <li class="active">Companies Detail</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <!-- Horizontal Form -->
          <div class="box box-default">
            <div class="box-header with-border">
              <h3 class="box-title">Companies Detail</h3>
            </div>
            <!-- /.box-header -->

            @if ($errors->any())
              <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                      <li>{{ $error }}</li>
                    @endforeach
                </ul>
              </div><br />
            @endif
            <!-- form start -->
            <form class="form-horizontal" method="POST" action="{{ route('companies.store') }}" enctype="multipart/form-data">
              @csrf
              <div class="box-body">
                <div class="col-md-6">
                  <table class="table">
                    <tr>
                      <th>Name</th>
                      <td>{{ $companies->name }}</td>
                    </tr>
                    <tr>
                      <th>Email</th>
                      <td>{{ $companies->email }}</td>
                    </tr>
                    <tr>
                      <th>Logo</th>
                      <td>
                        {{ $companies->logo }}
                      </td>
                    </tr>
                    <tr>
                      <td></td>
                      <td><img src="{{ asset('storage/company/').'/'.$companies->logo }}" id="preview-logo" width="200px" /></td>
                    </tr>
                    <tr>
                      <th>Website</th>
                      <td>{{ $companies->website }}</td>
                    </tr>
                  </table>
                  <!-- <div class="form-group">
                    <label for="name" class="col-sm-2 control-label">Name</label>
                    {{ $companies->name }}
                  </div>
                  <label for="name" class="col-sm-2 control-label">Email</label>
                  <span>{{ $companies->email }}</span>

                  <label for="name" class="col-sm-2 control-label">Logo</label>
                  <span>{{ $companies->logo }}</span>
                  <img src="{{ asset('images/').'/'.$companies->logo }}" id="preview-logo" width="200px" />

                  <label for="name" class="col-sm-2 control-label">Website</label>
                  <span>{{ $companies->website }}</span> -->
                </div>
              </div>
              <!-- /.box-body -->
              <div class="box-footer">
                <a href="{{ route('companies.index') }}" type="button" class="btn btn-default"><i class="fa fa-arrow-left"></i> Back</a>
              </div>
              <!-- /.box-footer -->
            </form>
          </div>
        </div>
      </div>
    </section>
@endsection

@section('scripts')
<script type="text/javascript">
  function readURL(input) {
      if (input.files && input.files[0]) {
          var reader = new FileReader();
          
          reader.onload = function (e) {
              $('#preview-logo').attr('src', e.target.result);
          }
          
          reader.readAsDataURL(input.files[0]);
      }
  }
  
  $("#logo").change(function(){
      readURL(this);
  });
</script>
@endsection

resources/views/companies/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
      <h1>
        Companies
        <small>preview of simple tables</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Companies</a></li>
        <li class="active">Companies Edit</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <!-- Horizontal Form -->
          <div class="box box-default">
            <div class="box-header with-border">
              <h3 class="box-title">Companies Edit</h3>
            </div>
            <!-- /.box-header -->

            @if ($errors->any())
              <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                      <li>{{ $error }}</li>
                    @endforeach
                </ul>
              </div><br />
            @endif
            <!-- form start -->
            <form class="form-horizontal" method="POST" action="{{ route('companies.update', $companies->id) }}" enctype="multipart/form-data">
              {{ method_field('PUT') }}
              @csrf
              <div class="box-body">
                <div class="form-group">
                  <label for="name" class="col-sm-2 control-label">Name</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control" name="name" placeholder="Name" value="{{ $companies->name }}">
                  </div>
                </div>
                <div class="form-group">
                  <label for="email" class="col-sm-2 control-label">Email</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control" name="email" placeholder="Email" value="{{ $companies->email }}">
                  </div>
                </div>
                <div class="form-group">
                  <label for="logo" class="col-sm-2 control-label">Logo</label>
                  <div class="col-sm-8">
                    <input type="file" id="logo" class="form-control" name="logo" placeholder="Logo" value="{{ $companies->logo }}">
                    <br>
                    <img src="{{ asset('storage/company/').'/'.$companies->logo }}" id="preview-logo" width="200px" />
                  </div>
                </div>
                <div class="form-group">
                  <label for="website" class="col-sm-2 control-label">Website</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control" name="website" placeholder="Website" value="{{ $companies->website }}">
                  </div>
                </div>
              </div>
              <!-- /.box-body -->
              <div class="box-footer">
                <a href="{{ route('companies.index') }}" type="button" class="btn btn-default"><i class="fa fa-arrow-left"></i> Back</a>
                <button type="submit" class="btn btn-success pull-right"><i class="fa fa-save"></i> Update</button>
              </div>
              <!-- /.box-footer -->
            </form>
          </div>
        </div>
      </div>
    </section>
@endsection

@section('scripts')
<script type="text/javascript">
  function readURL(input) {
      if (input.files && input.files[0]) {
          var reader = new FileReader();
          
          reader.onload = function (e) {
              $('#preview-logo').attr('src', e.target.result);
          }
          
          reader.readAsDataURL(input.files[0]);
      }
  }
  
  $("#logo").change(function(){
      readURL(this);
  });
</script>
@endsection

resources/views/companies/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
      <h1>
        Companies
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Companies</a></li>
        <li class="active">Companies Data</li>
      </ol>
    </section>


    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-12">
            @if (session('success'))
                <div class="alert alert-success">
                    {{ session('success') }}
                </div>
            @endif
          <div class="box">
            <div class="box-header with-border">
              <h3 class="box-title">Companies Data</h3>
              <div class="pull-right box-tools">
                <a href="{{ route('companies.create') }}" type="button" class="btn btn-sm btn-primary" >
                  <i class="fa fa-plus"></i> Create
                </a>
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table class="table table-bordered">
                <tr>
                  <th style="width: 10px">No</th>
                  <th>Name</th>
                  <th>Email</th>
                  <th colspan="2">Logo</th>
                  <th>Website</th>
                  <th>Action</th>
                </tr>
                  <?php $no=($companies->currentpage()-1)* $companies->perpage() + 1; ?>
                @foreach($companies as $c)
                    <tr>
                        <td>{{ $no }}</td>
                        <td>{{ $c->name }}</td>
                        <td>{{ $c->email }}</td>
                        <td>
                            {{ $c->logo }}
                        </td>
                        <td class="text-center">
                            <img src="{{ asset('storage/company/').'/'.$c->logo }}" id="preview-logo" width="50px" />
                        </td>
                        <td>{{ $c->website }}</td>
                        <td>
                            <form action="{{ route('companies.destroy', $c->id)}}" method="post">
                              <a href="{{ route('companies.show', $c->id) }}" class="btn btn-xs btn-info"><i class="fa fa-eye"></i> Show</a>
                              <a href="{{ route('companies.edit', $c->id) }}" class="btn btn-xs btn-warning"><i class="fa fa-pencil"></i> Edit</a>
                              @csrf
                              @method('DELETE')
                              <button class="btn btn-xs btn-danger" type="submit"><i class="fa fa-trash"></i>Delete</button>
                            </form>
                        </td>
                        <?php $no++ ?>
                    </tr>
                @endforeach
              </table>
            </div>
            <!-- /.box-body -->
            <div class="box-footer clearfix">
              <ul class="pagination pagination-sm no-margin pull-right">
                {{ $companies->links() }}
              </ul>
            </div>
          </div>
          <!-- /.box -->
        </div>
      </div>
    </section>
@endsection

@section('scripts')
<script type="text/javascript">
    
  function destroy(id) {
    swal({
      title: "Are you sure to delete this data?",
      icon: "warning",
      buttons: true,
      dangerMode: true,
    })
    .then((willDelete) => {
      if (willDelete) {
        $.ajax({
          type: 'DELETE',
          dataType: 'JSON',
          url: "",
          data: {
            _token: "{{ csrf_token() }}",
            id: id
          },
          success: function(res) {
            toastr.success('Successfully', 'Data has been deleted.')
            setTimeout(function(){
               window.location.reload();
            }, 1000);
          }
        })
      }

    });
  }
</script>
@endsection