routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth/login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
// Route::get('/companies', 'CompaniesController@index')->name('companies');
// Route::post('/companies/store', 'CompaniesController@store')->name('companies-store');
Route::resource('companies', 'CompaniesController');
Route::resource('employees', 'EmployeesController');
// Route::get('/employees', 'EmployeesController@index')->name('employees');

app/Employees.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Model;

class Employees extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'companies_id', 'email'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
}

app/Http/Controllers/EmployeesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use App\Employees;
use App\Companies;

class EmployeesController extends Controller
{
    
    public function __construct() {
        $this->middleware("auth");
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employees = DB::table('employees')->select('employees.id', 'employees.name as employees_name', 'companies.id as companies_id', 'companies.name as companies_name', 'employees.email')->join('companies', 'companies.id', '=', 'employees.companies_id')->paginate(5);
        return view('employees.index', ['employees' => $employees]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $items = Companies::all('name', 'id');
        return view('employees.create', ['items' => $items]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'companies_id' => 'required',
            'email' => 'required|unique:employees',
        ]);
     
        $employees = new Employees([
            'name' => $request->get('name'),
            'companies_id'=> $request->get('companies_id'),
            'email'=> $request->get('email'),
        ]);
        $employees->save();
        return redirect('/employees')->with('success', 'Employees has been added Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $employees = Employees::find($id);
        $items = Companies::all('name', 'id');
        return view('employees.edit', ['employees' => $employees, 'items' => $items]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $employees = Employees::find($id);

        if ($employees->email == $request->get('email')) {
            $request->validate([
                'name' => 'required',
                'companies_id' => 'required',
                'email' => 'required|email',
            ]);
        } else {
            $request->validate([
                'name' => 'required',
                'companies_id' => 'required',
                'email' => 'required|email|unique:employees,email,{$this->post->id}',
            ]);
        }
     
        $employees->name = $request->get('name');
        $employees->companies_id = $request->get('companies_id');
        $employees->email = $request->get('email');
        $employees->update();
        return redirect('/employees')->with('success', 'Employees has been updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $employees = Employees::find($id);
        $employees->delete();

        return redirect('/employees')->with('success', 'Employees has been deleted Successfully');
    }
}

resources/views/employees/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
      <h1>
        Employees
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Employees</a></li>
        <li class="active">Employees Create</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-12">
            @if ($errors->any())
              <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                      <li>{{ $error }}</li>
                    @endforeach
                </ul>
              </div>
            @endif
          <!-- Horizontal Form -->
          <div class="box box-default">
            <div class="box-header with-border">
              <h3 class="box-title">Employees Create</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form class="form-horizontal" method="POST" action="{{ route('employees.store') }}" enctype="multipart/form-data">
              @csrf
              <div class="box-body">
                <div class="form-group">
                  <label for="name" class="col-sm-2 control-label">Name</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control" name="name" placeholder="Name" value="{{ old('name') }}">
                  </div>
                </div>
                <div class="form-group">
                  <label for="companies_id" class="col-sm-2 control-label">Companies</label>
                  <div class="col-sm-8">
                    <select name="companies_id" id="companies_id" class="form-control select2">
                      <option value="">-- Choose Companies --</option>
                      @foreach($items as $i )
                        <option value="{{ $i->id }}" 
                        @if (old('companies_id') == $i->id) selected="selected" @endif
                        >{{ $i->name }}</option>
                      @endforeach
                    </select>
                  </div>
                </div>
                <div class="form-group">
                  <label for="email" class="col-sm-2 control-label">Email</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control" name="email" placeholder="Email" value="{{ old('email') }}">
                  </div>
                </div>
              </div>
              <!-- /.box-body -->
              <div class="box-footer">
                <a href="{{ route('employees.index') }}" type="button" class="btn btn-default"><i class="fa fa-arrow-left"></i> Back</a>
                <button type="submit" class="btn btn-success pull-right"><i class="fa fa-save"></i> Save</button>
              </div>
              <!-- /.box-footer -->
            </form>
          </div>
        </div>
      </div>
    </section>
@endsection

@section('scripts')
<script type="text/javascript">
  $(document).ready(function(){
    $('.select2').select2();
  })
</script>
@endsection

resources/views/employees/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
      <h1>
        Employees
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Employees</a></li>
        <li class="active">Employees Edit</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <!-- Horizontal Form -->
          <div class="box box-default">
            <div class="box-header with-border">
              <h3 class="box-title">Employees Edit</h3>
            </div>
            <!-- /.box-header -->

            @if ($errors->any())
              <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                      <li>{{ $error }}</li>
                    @endforeach
                </ul>
              </div><br />
            @endif
            <!-- form start -->
            <form class="form-horizontal" method="POST" action="{{ route('employees.update', $employees->id) }}">
              {{ method_field('PUT') }}
              @csrf
              <div class="box-body">
                <div class="form-group">
                  <label for="name" class="col-sm-2 control-label">Name</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control" name="name" placeholder="Name" value="{{ $employees->name }}">
                  </div>
                </div>
                <div class="form-group">
                  <label for="companies_id" class="col-sm-2 control-label">Companies</label>
                  <div class="col-sm-8">
                    <select name="companies_id" id="companies_id" class="form-control">
                      <option value="">-- Choose Companies --</option>
                      @foreach($items as $i )
                        <option value="{{ $i->id }}" {{$employees->companies_id == $i->id  ? 'selected' : ''}}>{{ $i->name }}</option>
                      @endforeach
                    </select>
                  </div>
                </div>
                <div class="form-group">
                  <label for="email" class="col-sm-2 control-label">Email</label>
                  <div class="col-sm-8">
                    <input type="text" class="form-control" name="email" placeholder="Email" value="{{ $employees->email }}">
                  </div>
                </div>
              </div>
              <!-- /.box-body -->
              <div class="box-footer">
                <a href="{{ route('employees.index') }}" type="button" class="btn btn-default"><i class="fa fa-arrow-left"></i> Back</a>
                <button type="submit" class="btn btn-success pull-right"><i class="fa fa-save"></i> Update</button>
              </div>
              <!-- /.box-footer -->
            </form>
          </div>
        </div>
      </div>
    </section>
@endsection

@section('scripts')
<script type="text/javascript">

</script>
@endsection

resources/views/employees/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
      <h1>
        Employees
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Employees</a></li>
        <li class="active">Employees Data</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-12">
          @if (session('success'))
              <div class="alert alert-success">
                  {{ session('success') }}
              </div>
          @endif
          <div class="box">
            <div class="box-header with-border">
              <h3 class="box-title">Employees Data</h3>
              <div class="pull-right box-tools">
                <a href="{{ route('employees.create') }}" type="button" class="btn btn-sm btn-primary" >
                  <i class="fa fa-plus"></i> Add
                </a>
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table class="table table-bordered">
                <tr>
                  <th style="width: 10px">No</th>
                  <th>Name</th>
                  <th>Companies</th>
                  <th>Email</th>
                  <th>Action</th>
                </tr>
                  <?php $no=($employees->currentpage()-1)* $employees->perpage() + 1; ?>
                @foreach($employees as $e)
                    <tr>
                        <td>{{ $no }}</td>
                        <td>{{ $e->employees_name }}</td>
                        <td>
                          <a href="{{ route('companies.show', $e->companies_id) }}">{{ $e->companies_name }}</a>
                        </td>
                        <td>{{ $e->email }}</td>
                        <td>
                            <form action="{{ route('employees.destroy', $e->id)}}" method="post">
                              <a href="{{ route('employees.edit', $e->id) }}" class="btn btn-xs btn-warning"><i class="fa fa-pencil"></i> Edit</a>
                              @csrf
                              @method('DELETE')
                              <button class="btn btn-xs btn-danger" type="submit"><i class="fa fa-trash"></i> Delete</button>
                            </form>
                        </td>
                        <?php $no++ ?>
                    </tr>
                @endforeach
              </table>
            </div>
            <!-- /.box-body -->
            <div class="box-footer clearfix">
              <ul class="pagination pagination-sm no-margin pull-right">
                {{ $employees->links() }}
              </ul>
            </div>
          </div>
          <!-- /.box -->
        </div>
      </div>
    </section>
@endsection